import type { ToolContent } from "@/lib/seo";

export const content: ToolContent = {
  title: "ASCII Art Generator",
  description:
    "Convert text to ASCII art using FIGlet-style fonts. Choose from Standard, Banner, Big, and Small fonts. Free online tool that runs entirely in your browser.",
  whatIs:
    "ASCII art is a graphic design technique that uses printable characters from the ASCII standard to create visual representations of text and images. FIGlet (Frank, Ian & Glenn's Letters) is a classic program that generates text banners in various typefaces composed of regular characters. This tool converts your text into large, decorative ASCII art using four built-in fonts, perfect for terminal headers, code comments, README files, and retro-style decorations.",
  howToUse:
    "Type your text into the input field and select a font from the dropdown. The ASCII art preview updates in real time. Use the copy button to copy the generated art to your clipboard. The character width indicator shows how wide your output is, helping you ensure it fits within terminal or code editor widths.",
  howItWorks:
    "Each font is defined as a character map where every letter, digit, and space is represented by an array of text lines. When you type, the tool looks up each character in the selected font and concatenates the corresponding lines side by side to form the final output. All processing happens client-side in your browser with zero dependencies.",
  useCases: [
    "Creating eye-catching headers for terminal applications and CLI tools",
    "Adding decorative banners to source code comments and README files",
    "Generating retro-style text art for emails, forums, and chat messages",
    "Building welcome screens and splash text for server applications",
    "Designing text-based logos for projects and open-source libraries",
    "Adding personality to commit messages or pull request descriptions",
  ],
  faq: [
    {
      q: "What fonts are available?",
      a: "The tool includes four fonts: Standard (classic FIGlet style), Banner (large block letters using # characters), Big (tall decorative letters), and Small (compact ASCII art). Each font has full support for A-Z uppercase letters, 0-9 digits, and spaces.",
    },
    {
      q: "Does this tool support lowercase letters?",
      a: "The tool automatically converts input to uppercase for rendering, since the ASCII art fonts are designed for uppercase characters. Your input can be typed in any case.",
    },
    {
      q: "How wide can the output be?",
      a: "The width depends on your text length and the chosen font. The character width indicator shows the current output width. Most terminals default to 80 characters wide, so keep an eye on the width indicator to ensure your art fits.",
    },
    {
      q: "Does this tool send my data to a server?",
      a: "No. All text-to-ASCII-art conversion happens entirely in your browser using JavaScript. Your text never leaves your device.",
    },
    {
      q: "Can I use the generated ASCII art commercially?",
      a: "Yes. The ASCII art generated by this tool is plain text output and is not subject to copyright restrictions. You are free to use it in any project, commercial or otherwise.",
    },
  ],
};
