export interface EmojiData {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
}

export const CATEGORIES = [
  "Smileys & Emotion",
  "Gestures & People",
  "Animals & Nature",
  "Food & Drink",
  "Travel & Places",
  "Objects",
  "Symbols",
  "Flags",
] as const;

export type EmojiCategory = (typeof CATEGORIES)[number];

export const SKIN_TONES = [
  { label: "Default", modifier: "" },
  { label: "Light", modifier: "\u{1F3FB}" },
  { label: "Medium-Light", modifier: "\u{1F3FC}" },
  { label: "Medium", modifier: "\u{1F3FD}" },
  { label: "Medium-Dark", modifier: "\u{1F3FE}" },
  { label: "Dark", modifier: "\u{1F3FF}" },
] as const;

export const SKIN_TONE_PREVIEW = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"];

// Check if an emoji supports skin tones (has a ZWJ or is a base emoji that accepts modifiers)
export function supportsSkinTone(emoji: string): boolean {
  // Test by appending a skin tone and checking if it renders as a single grapheme
  // Simpler approach: maintain a list of base code points that accept skin tones
  const cp = emoji.codePointAt(0);
  if (!cp) return false;
  // Unicode ranges for emoji that accept skin tone modifiers
  const skinToneRanges = [
    [0x261D, 0x261D], // index pointing up
    [0x26F9, 0x26F9], // person bouncing ball
    [0x270A, 0x270D], // fists, hands, writing hand
    [0x1F385, 0x1F385], // Santa
    [0x1F3C2, 0x1F3C4], // sports
    [0x1F3C7, 0x1F3C7],
    [0x1F3CA, 0x1F3CC],
    [0x1F442, 0x1F443], // ear, nose
    [0x1F446, 0x1F450], // pointing, hands
    [0x1F466, 0x1F478], // people
    [0x1F47C, 0x1F47C],
    [0x1F481, 0x1F483],
    [0x1F485, 0x1F487],
    [0x1F48F, 0x1F48F],
    [0x1F491, 0x1F491],
    [0x1F4AA, 0x1F4AA], // flexed biceps
    [0x1F574, 0x1F575],
    [0x1F57A, 0x1F57A],
    [0x1F590, 0x1F590],
    [0x1F595, 0x1F596],
    [0x1F645, 0x1F647],
    [0x1F64B, 0x1F64F],
    [0x1F6A3, 0x1F6A3],
    [0x1F6B4, 0x1F6B6],
    [0x1F6C0, 0x1F6C0],
    [0x1F6CC, 0x1F6CC],
    [0x1F90C, 0x1F90C],
    [0x1F90F, 0x1F90F],
    [0x1F918, 0x1F91F],
    [0x1F926, 0x1F926],
    [0x1F930, 0x1F939],
    [0x1F93D, 0x1F93E],
    [0x1F9B5, 0x1F9B6],
    [0x1F9B8, 0x1F9B9],
    [0x1F9BB, 0x1F9BB],
    [0x1F9CD, 0x1F9CF],
    [0x1F9D1, 0x1F9DD],
    [0x1FAC3, 0x1FAC5],
    [0x1FAF0, 0x1FAF6],
  ];
  return skinToneRanges.some(([lo, hi]) => cp >= lo && cp <= hi);
}

export function applySkinTone(emoji: string, modifier: string): string {
  if (!modifier || !supportsSkinTone(emoji)) return emoji;
  // Remove any existing skin tone modifier first
  const base = emoji.replace(
    new RegExp("[\u{1F3FB}-\u{1F3FF}]", "g"),
    ""
  );
  // Insert skin tone after the first code point
  const chars = Array.from(base);
  if (chars.length === 0) return emoji;
  return chars[0] + modifier + chars.slice(1).join("");
}

export const ALL_EMOJIS: EmojiData[] = [
  // ── Smileys & Emotion ──
  { emoji: "\u{1F600}", name: "Grinning Face", category: "Smileys & Emotion", keywords: ["smile", "happy", "joy"] },
  { emoji: "\u{1F603}", name: "Grinning Face with Big Eyes", category: "Smileys & Emotion", keywords: ["smile", "happy"] },
  { emoji: "\u{1F604}", name: "Grinning Face with Smiling Eyes", category: "Smileys & Emotion", keywords: ["smile", "happy", "joy"] },
  { emoji: "\u{1F601}", name: "Beaming Face with Smiling Eyes", category: "Smileys & Emotion", keywords: ["smile", "happy", "grin"] },
  { emoji: "\u{1F606}", name: "Grinning Squinting Face", category: "Smileys & Emotion", keywords: ["laugh", "happy", "haha"] },
  { emoji: "\u{1F605}", name: "Grinning Face with Sweat", category: "Smileys & Emotion", keywords: ["relief", "sweat", "nervous"] },
  { emoji: "\u{1F923}", name: "Rolling on the Floor Laughing", category: "Smileys & Emotion", keywords: ["laugh", "rofl", "lol", "funny"] },
  { emoji: "\u{1F602}", name: "Face with Tears of Joy", category: "Smileys & Emotion", keywords: ["laugh", "cry", "happy", "tears", "lol"] },
  { emoji: "\u{1F642}", name: "Slightly Smiling Face", category: "Smileys & Emotion", keywords: ["smile", "ok"] },
  { emoji: "\u{1F643}", name: "Upside-Down Face", category: "Smileys & Emotion", keywords: ["sarcasm", "silly", "upside down"] },
  { emoji: "\u{1F609}", name: "Winking Face", category: "Smileys & Emotion", keywords: ["wink", "flirt"] },
  { emoji: "\u{1F60A}", name: "Smiling Face with Smiling Eyes", category: "Smileys & Emotion", keywords: ["blush", "happy", "warm"] },
  { emoji: "\u{1F607}", name: "Smiling Face with Halo", category: "Smileys & Emotion", keywords: ["angel", "innocent", "halo"] },
  { emoji: "\u{1F970}", name: "Smiling Face with Hearts", category: "Smileys & Emotion", keywords: ["love", "hearts", "adore"] },
  { emoji: "\u{1F60D}", name: "Smiling Face with Heart-Eyes", category: "Smileys & Emotion", keywords: ["love", "heart", "crush"] },
  { emoji: "\u{1F929}", name: "Star-Struck", category: "Smileys & Emotion", keywords: ["star", "eyes", "wow", "amazing"] },
  { emoji: "\u{1F618}", name: "Face Blowing a Kiss", category: "Smileys & Emotion", keywords: ["kiss", "love", "mwah"] },
  { emoji: "\u{1F617}", name: "Kissing Face", category: "Smileys & Emotion", keywords: ["kiss", "lips"] },
  { emoji: "\u{263A}\u{FE0F}", name: "Smiling Face", category: "Smileys & Emotion", keywords: ["smile", "warm", "classic"] },
  { emoji: "\u{1F61A}", name: "Kissing Face with Closed Eyes", category: "Smileys & Emotion", keywords: ["kiss", "love"] },
  { emoji: "\u{1F61B}", name: "Face with Tongue", category: "Smileys & Emotion", keywords: ["tongue", "playful", "silly"] },
  { emoji: "\u{1F61D}", name: "Squinting Face with Tongue", category: "Smileys & Emotion", keywords: ["tongue", "silly", "playful"] },
  { emoji: "\u{1F61C}", name: "Winking Face with Tongue", category: "Smileys & Emotion", keywords: ["wink", "tongue", "silly"] },
  { emoji: "\u{1F92A}", name: "Zany Face", category: "Smileys & Emotion", keywords: ["crazy", "wild", "silly", "goofy"] },
  { emoji: "\u{1F928}", name: "Face with Raised Eyebrow", category: "Smileys & Emotion", keywords: ["skeptic", "suspicious", "doubt"] },
  { emoji: "\u{1F9D0}", name: "Face with Monocle", category: "Smileys & Emotion", keywords: ["fancy", "monocle", "inspect"] },
  { emoji: "\u{1F913}", name: "Nerd Face", category: "Smileys & Emotion", keywords: ["nerd", "geek", "glasses", "smart"] },
  { emoji: "\u{1F60E}", name: "Smiling Face with Sunglasses", category: "Smileys & Emotion", keywords: ["cool", "sunglasses", "awesome"] },
  { emoji: "\u{1F60F}", name: "Smirking Face", category: "Smileys & Emotion", keywords: ["smirk", "flirt", "sly"] },
  { emoji: "\u{1F612}", name: "Unamused Face", category: "Smileys & Emotion", keywords: ["unamused", "annoyed", "bored"] },
  { emoji: "\u{1F61E}", name: "Disappointed Face", category: "Smileys & Emotion", keywords: ["sad", "disappointed"] },
  { emoji: "\u{1F614}", name: "Pensive Face", category: "Smileys & Emotion", keywords: ["sad", "pensive", "thoughtful"] },
  { emoji: "\u{1F61F}", name: "Worried Face", category: "Smileys & Emotion", keywords: ["worried", "anxious", "concern"] },
  { emoji: "\u{1F615}", name: "Confused Face", category: "Smileys & Emotion", keywords: ["confused", "puzzled"] },
  { emoji: "\u{1F641}", name: "Slightly Frowning Face", category: "Smileys & Emotion", keywords: ["frown", "sad"] },
  { emoji: "\u{2639}\u{FE0F}", name: "Frowning Face", category: "Smileys & Emotion", keywords: ["sad", "frown", "unhappy"] },
  { emoji: "\u{1F623}", name: "Persevering Face", category: "Smileys & Emotion", keywords: ["struggle", "frustration"] },
  { emoji: "\u{1F616}", name: "Confounded Face", category: "Smileys & Emotion", keywords: ["quiver", "frustrated"] },
  { emoji: "\u{1F62B}", name: "Tired Face", category: "Smileys & Emotion", keywords: ["tired", "exhausted", "sick"] },
  { emoji: "\u{1F629}", name: "Weary Face", category: "Smileys & Emotion", keywords: ["weary", "tired", "frustrated"] },
  { emoji: "\u{1F622}", name: "Crying Face", category: "Smileys & Emotion", keywords: ["cry", "sad", "tear"] },
  { emoji: "\u{1F62D}", name: "Loudly Crying Face", category: "Smileys & Emotion", keywords: ["sob", "cry", "sad", "tears"] },
  { emoji: "\u{1F624}", name: "Face with Steam from Nose", category: "Smileys & Emotion", keywords: ["angry", "frustrated", "steam"] },
  { emoji: "\u{1F620}", name: "Angry Face", category: "Smileys & Emotion", keywords: ["angry", "mad", "furious"] },
  { emoji: "\u{1F621}", name: "Pouting Face", category: "Smileys & Emotion", keywords: ["angry", "rage", "red"] },
  { emoji: "\u{1F92C}", name: "Face with Symbols on Mouth", category: "Smileys & Emotion", keywords: ["swear", "curse", "angry"] },
  { emoji: "\u{1F92F}", name: "Exploding Head", category: "Smileys & Emotion", keywords: ["mind blown", "shocked", "wow"] },
  { emoji: "\u{1F633}", name: "Flushed Face", category: "Smileys & Emotion", keywords: ["embarrassed", "blush", "shocked"] },
  { emoji: "\u{1F631}", name: "Face Screaming in Fear", category: "Smileys & Emotion", keywords: ["scream", "scared", "horror"] },
  { emoji: "\u{1F628}", name: "Fearful Face", category: "Smileys & Emotion", keywords: ["fear", "scared", "worried"] },
  { emoji: "\u{1F630}", name: "Anxious Face with Sweat", category: "Smileys & Emotion", keywords: ["anxious", "nervous", "sweat"] },
  { emoji: "\u{1F625}", name: "Sad but Relieved Face", category: "Smileys & Emotion", keywords: ["relief", "sad", "sweat"] },
  { emoji: "\u{1F917}", name: "Hugging Face", category: "Smileys & Emotion", keywords: ["hug", "warm", "love"] },
  { emoji: "\u{1F914}", name: "Thinking Face", category: "Smileys & Emotion", keywords: ["think", "hmm", "wonder", "ponder"] },
  { emoji: "\u{1F92D}", name: "Face with Hand Over Mouth", category: "Smileys & Emotion", keywords: ["oops", "giggle", "cover"] },
  { emoji: "\u{1F92B}", name: "Shushing Face", category: "Smileys & Emotion", keywords: ["quiet", "shh", "secret"] },
  { emoji: "\u{1F925}", name: "Lying Face", category: "Smileys & Emotion", keywords: ["lie", "pinocchio", "liar"] },
  { emoji: "\u{1F636}", name: "Face Without Mouth", category: "Smileys & Emotion", keywords: ["silent", "speechless", "mute"] },
  { emoji: "\u{1F610}", name: "Neutral Face", category: "Smileys & Emotion", keywords: ["neutral", "blank", "meh"] },
  { emoji: "\u{1F611}", name: "Expressionless Face", category: "Smileys & Emotion", keywords: ["expressionless", "blank", "bored"] },
  { emoji: "\u{1F62C}", name: "Grimacing Face", category: "Smileys & Emotion", keywords: ["grimace", "awkward", "cringe"] },
  { emoji: "\u{1F644}", name: "Face with Rolling Eyes", category: "Smileys & Emotion", keywords: ["eye roll", "annoyed", "whatever"] },
  { emoji: "\u{1F62F}", name: "Hushed Face", category: "Smileys & Emotion", keywords: ["hushed", "surprised", "wow"] },
  { emoji: "\u{1F626}", name: "Frowning Face with Open Mouth", category: "Smileys & Emotion", keywords: ["frown", "surprise", "shock"] },
  { emoji: "\u{1F627}", name: "Anguished Face", category: "Smileys & Emotion", keywords: ["anguish", "pain", "ouch"] },
  { emoji: "\u{1F62E}", name: "Face with Open Mouth", category: "Smileys & Emotion", keywords: ["surprise", "gasp", "wow"] },
  { emoji: "\u{1F632}", name: "Astonished Face", category: "Smileys & Emotion", keywords: ["astonished", "amazed", "shocked"] },
  { emoji: "\u{1F971}", name: "Yawning Face", category: "Smileys & Emotion", keywords: ["yawn", "tired", "bored", "sleepy"] },
  { emoji: "\u{1F634}", name: "Sleeping Face", category: "Smileys & Emotion", keywords: ["sleep", "zzz", "tired"] },
  { emoji: "\u{1F924}", name: "Drooling Face", category: "Smileys & Emotion", keywords: ["drool", "hungry", "yummy"] },
  { emoji: "\u{1F62A}", name: "Sleepy Face", category: "Smileys & Emotion", keywords: ["sleepy", "tired"] },
  { emoji: "\u{1F635}", name: "Face with Crossed-Out Eyes", category: "Smileys & Emotion", keywords: ["dizzy", "dead", "knocked out"] },
  { emoji: "\u{1F910}", name: "Zipper-Mouth Face", category: "Smileys & Emotion", keywords: ["zip", "secret", "quiet", "shut up"] },
  { emoji: "\u{1F974}", name: "Woozy Face", category: "Smileys & Emotion", keywords: ["drunk", "dizzy", "woozy"] },
  { emoji: "\u{1F922}", name: "Nauseated Face", category: "Smileys & Emotion", keywords: ["sick", "nausea", "green", "vomit"] },
  { emoji: "\u{1F92E}", name: "Face Vomiting", category: "Smileys & Emotion", keywords: ["vomit", "sick", "throw up"] },
  { emoji: "\u{1F927}", name: "Sneezing Face", category: "Smileys & Emotion", keywords: ["sneeze", "tissue", "cold", "sick"] },
  { emoji: "\u{1F637}", name: "Face with Medical Mask", category: "Smileys & Emotion", keywords: ["mask", "sick", "doctor", "cold"] },
  { emoji: "\u{1F912}", name: "Face with Thermometer", category: "Smileys & Emotion", keywords: ["sick", "fever", "ill"] },
  { emoji: "\u{1F915}", name: "Face with Head-Bandage", category: "Smileys & Emotion", keywords: ["hurt", "injured", "bandage"] },
  { emoji: "\u{1F911}", name: "Money-Mouth Face", category: "Smileys & Emotion", keywords: ["money", "rich", "dollar"] },
  { emoji: "\u{1F920}", name: "Cowboy Hat Face", category: "Smileys & Emotion", keywords: ["cowboy", "hat", "western"] },

  // ── Gestures & People ──
  { emoji: "\u{1F44B}", name: "Waving Hand", category: "Gestures & People", keywords: ["wave", "hello", "goodbye", "hi"] },
  { emoji: "\u{1F91A}", name: "Raised Back of Hand", category: "Gestures & People", keywords: ["hand", "raised"] },
  { emoji: "\u{1F590}\u{FE0F}", name: "Hand with Fingers Splayed", category: "Gestures & People", keywords: ["hand", "fingers", "stop"] },
  { emoji: "\u{270B}", name: "Raised Hand", category: "Gestures & People", keywords: ["hand", "stop", "high five"] },
  { emoji: "\u{1F596}", name: "Vulcan Salute", category: "Gestures & People", keywords: ["spock", "star trek", "vulcan"] },
  { emoji: "\u{1F44C}", name: "OK Hand", category: "Gestures & People", keywords: ["ok", "perfect", "fine"] },
  { emoji: "\u{1F90C}", name: "Pinched Fingers", category: "Gestures & People", keywords: ["italian", "pinch", "what"] },
  { emoji: "\u{1F90F}", name: "Pinching Hand", category: "Gestures & People", keywords: ["small", "tiny", "pinch"] },
  { emoji: "\u{270C}\u{FE0F}", name: "Victory Hand", category: "Gestures & People", keywords: ["peace", "victory", "v"] },
  { emoji: "\u{1F91E}", name: "Crossed Fingers", category: "Gestures & People", keywords: ["luck", "hope", "fingers crossed"] },
  { emoji: "\u{1F91F}", name: "Love-You Gesture", category: "Gestures & People", keywords: ["love", "ily", "rock"] },
  { emoji: "\u{1F918}", name: "Sign of the Horns", category: "Gestures & People", keywords: ["rock", "metal", "horns"] },
  { emoji: "\u{1F919}", name: "Call Me Hand", category: "Gestures & People", keywords: ["call", "shaka", "hang loose"] },
  { emoji: "\u{1F448}", name: "Backhand Index Pointing Left", category: "Gestures & People", keywords: ["left", "point"] },
  { emoji: "\u{1F449}", name: "Backhand Index Pointing Right", category: "Gestures & People", keywords: ["right", "point"] },
  { emoji: "\u{1F446}", name: "Backhand Index Pointing Up", category: "Gestures & People", keywords: ["up", "point"] },
  { emoji: "\u{1F595}", name: "Middle Finger", category: "Gestures & People", keywords: ["finger", "rude"] },
  { emoji: "\u{1F447}", name: "Backhand Index Pointing Down", category: "Gestures & People", keywords: ["down", "point"] },
  { emoji: "\u{261D}\u{FE0F}", name: "Index Pointing Up", category: "Gestures & People", keywords: ["up", "point", "one"] },
  { emoji: "\u{1FAF5}", name: "Index Pointing at the Viewer", category: "Gestures & People", keywords: ["you", "point"] },
  { emoji: "\u{1F44D}", name: "Thumbs Up", category: "Gestures & People", keywords: ["like", "approve", "yes", "good", "thumbsup"] },
  { emoji: "\u{1F44E}", name: "Thumbs Down", category: "Gestures & People", keywords: ["dislike", "disapprove", "no", "bad"] },
  { emoji: "\u{270A}", name: "Raised Fist", category: "Gestures & People", keywords: ["fist", "power", "strong"] },
  { emoji: "\u{1F44A}", name: "Oncoming Fist", category: "Gestures & People", keywords: ["punch", "fist bump"] },
  { emoji: "\u{1F91B}", name: "Left-Facing Fist", category: "Gestures & People", keywords: ["fist", "bump"] },
  { emoji: "\u{1F91C}", name: "Right-Facing Fist", category: "Gestures & People", keywords: ["fist", "bump"] },
  { emoji: "\u{1F44F}", name: "Clapping Hands", category: "Gestures & People", keywords: ["clap", "applause", "bravo"] },
  { emoji: "\u{1FAF6}", name: "Heart Hands", category: "Gestures & People", keywords: ["love", "heart", "hands"] },
  { emoji: "\u{1F64C}", name: "Raising Hands", category: "Gestures & People", keywords: ["celebration", "hooray", "praise"] },
  { emoji: "\u{1F450}", name: "Open Hands", category: "Gestures & People", keywords: ["open", "hands", "jazz"] },
  { emoji: "\u{1F932}", name: "Palms Up Together", category: "Gestures & People", keywords: ["prayer", "palms"] },
  { emoji: "\u{1F91D}", name: "Handshake", category: "Gestures & People", keywords: ["deal", "agreement", "handshake"] },
  { emoji: "\u{1F64F}", name: "Folded Hands", category: "Gestures & People", keywords: ["pray", "please", "thank you", "namaste"] },
  { emoji: "\u{270D}\u{FE0F}", name: "Writing Hand", category: "Gestures & People", keywords: ["write", "pen"] },
  { emoji: "\u{1F485}", name: "Nail Polish", category: "Gestures & People", keywords: ["nails", "beauty", "sassy"] },
  { emoji: "\u{1F933}", name: "Selfie", category: "Gestures & People", keywords: ["selfie", "camera", "phone"] },
  { emoji: "\u{1F4AA}", name: "Flexed Biceps", category: "Gestures & People", keywords: ["strong", "muscle", "flex", "bicep"] },
  { emoji: "\u{1F442}", name: "Ear", category: "Gestures & People", keywords: ["ear", "listen", "hear"] },
  { emoji: "\u{1F443}", name: "Nose", category: "Gestures & People", keywords: ["nose", "smell"] },
  { emoji: "\u{1F440}", name: "Eyes", category: "Gestures & People", keywords: ["eyes", "look", "see", "watch"] },
  { emoji: "\u{1F441}\u{FE0F}", name: "Eye", category: "Gestures & People", keywords: ["eye", "see"] },
  { emoji: "\u{1F445}", name: "Tongue", category: "Gestures & People", keywords: ["tongue", "taste", "lick"] },
  { emoji: "\u{1F444}", name: "Mouth", category: "Gestures & People", keywords: ["mouth", "lips", "kiss"] },

  // ── Animals & Nature ──
  { emoji: "\u{1F436}", name: "Dog Face", category: "Animals & Nature", keywords: ["dog", "puppy", "pet"] },
  { emoji: "\u{1F431}", name: "Cat Face", category: "Animals & Nature", keywords: ["cat", "kitten", "pet"] },
  { emoji: "\u{1F42D}", name: "Mouse Face", category: "Animals & Nature", keywords: ["mouse", "rodent"] },
  { emoji: "\u{1F439}", name: "Hamster", category: "Animals & Nature", keywords: ["hamster", "pet"] },
  { emoji: "\u{1F430}", name: "Rabbit Face", category: "Animals & Nature", keywords: ["rabbit", "bunny"] },
  { emoji: "\u{1F98A}", name: "Fox", category: "Animals & Nature", keywords: ["fox", "cunning"] },
  { emoji: "\u{1F43B}", name: "Bear", category: "Animals & Nature", keywords: ["bear", "teddy"] },
  { emoji: "\u{1F43C}", name: "Panda", category: "Animals & Nature", keywords: ["panda", "bear", "cute"] },
  { emoji: "\u{1F428}", name: "Koala", category: "Animals & Nature", keywords: ["koala", "australia"] },
  { emoji: "\u{1F42F}", name: "Tiger Face", category: "Animals & Nature", keywords: ["tiger", "wild"] },
  { emoji: "\u{1F981}", name: "Lion", category: "Animals & Nature", keywords: ["lion", "king", "wild"] },
  { emoji: "\u{1F42E}", name: "Cow Face", category: "Animals & Nature", keywords: ["cow", "farm", "moo"] },
  { emoji: "\u{1F437}", name: "Pig Face", category: "Animals & Nature", keywords: ["pig", "farm", "oink"] },
  { emoji: "\u{1F438}", name: "Frog", category: "Animals & Nature", keywords: ["frog", "toad"] },
  { emoji: "\u{1F435}", name: "Monkey Face", category: "Animals & Nature", keywords: ["monkey", "primate"] },
  { emoji: "\u{1F648}", name: "See-No-Evil Monkey", category: "Animals & Nature", keywords: ["monkey", "see", "hide"] },
  { emoji: "\u{1F649}", name: "Hear-No-Evil Monkey", category: "Animals & Nature", keywords: ["monkey", "hear"] },
  { emoji: "\u{1F64A}", name: "Speak-No-Evil Monkey", category: "Animals & Nature", keywords: ["monkey", "speak", "quiet"] },
  { emoji: "\u{1F412}", name: "Monkey", category: "Animals & Nature", keywords: ["monkey", "primate"] },
  { emoji: "\u{1F414}", name: "Chicken", category: "Animals & Nature", keywords: ["chicken", "rooster", "bird"] },
  { emoji: "\u{1F427}", name: "Penguin", category: "Animals & Nature", keywords: ["penguin", "cold", "arctic"] },
  { emoji: "\u{1F426}", name: "Bird", category: "Animals & Nature", keywords: ["bird", "fly"] },
  { emoji: "\u{1F424}", name: "Baby Chick", category: "Animals & Nature", keywords: ["chick", "baby", "bird"] },
  { emoji: "\u{1F423}", name: "Hatching Chick", category: "Animals & Nature", keywords: ["chick", "hatching", "egg"] },
  { emoji: "\u{1F425}", name: "Front-Facing Baby Chick", category: "Animals & Nature", keywords: ["chick", "baby"] },
  { emoji: "\u{1F986}", name: "Duck", category: "Animals & Nature", keywords: ["duck", "quack"] },
  { emoji: "\u{1F985}", name: "Eagle", category: "Animals & Nature", keywords: ["eagle", "bird", "freedom"] },
  { emoji: "\u{1F989}", name: "Owl", category: "Animals & Nature", keywords: ["owl", "wise", "night"] },
  { emoji: "\u{1F987}", name: "Bat", category: "Animals & Nature", keywords: ["bat", "vampire", "night"] },
  { emoji: "\u{1F43A}", name: "Wolf", category: "Animals & Nature", keywords: ["wolf", "howl"] },
  { emoji: "\u{1F417}", name: "Boar", category: "Animals & Nature", keywords: ["boar", "pig", "wild"] },
  { emoji: "\u{1F434}", name: "Horse Face", category: "Animals & Nature", keywords: ["horse", "pony"] },
  { emoji: "\u{1F984}", name: "Unicorn", category: "Animals & Nature", keywords: ["unicorn", "magic", "fantasy"] },
  { emoji: "\u{1F41D}", name: "Honeybee", category: "Animals & Nature", keywords: ["bee", "honey", "buzz"] },
  { emoji: "\u{1F41B}", name: "Bug", category: "Animals & Nature", keywords: ["bug", "insect"] },
  { emoji: "\u{1F98B}", name: "Butterfly", category: "Animals & Nature", keywords: ["butterfly", "beautiful", "nature"] },
  { emoji: "\u{1F40C}", name: "Snail", category: "Animals & Nature", keywords: ["snail", "slow"] },
  { emoji: "\u{1F41E}", name: "Lady Beetle", category: "Animals & Nature", keywords: ["ladybug", "insect", "luck"] },
  { emoji: "\u{1F41C}", name: "Ant", category: "Animals & Nature", keywords: ["ant", "insect"] },
  { emoji: "\u{1F422}", name: "Turtle", category: "Animals & Nature", keywords: ["turtle", "slow", "shell"] },
  { emoji: "\u{1F40D}", name: "Snake", category: "Animals & Nature", keywords: ["snake", "reptile"] },
  { emoji: "\u{1F419}", name: "Octopus", category: "Animals & Nature", keywords: ["octopus", "sea"] },
  { emoji: "\u{1F333}", name: "Deciduous Tree", category: "Animals & Nature", keywords: ["tree", "nature"] },
  { emoji: "\u{1F332}", name: "Evergreen Tree", category: "Animals & Nature", keywords: ["tree", "pine", "christmas"] },
  { emoji: "\u{1F335}", name: "Cactus", category: "Animals & Nature", keywords: ["cactus", "desert"] },
  { emoji: "\u{1F33B}", name: "Sunflower", category: "Animals & Nature", keywords: ["sunflower", "flower", "sun"] },
  { emoji: "\u{1F339}", name: "Rose", category: "Animals & Nature", keywords: ["rose", "flower", "love"] },
  { emoji: "\u{1F33A}", name: "Hibiscus", category: "Animals & Nature", keywords: ["hibiscus", "flower"] },
  { emoji: "\u{1F337}", name: "Tulip", category: "Animals & Nature", keywords: ["tulip", "flower", "spring"] },
  { emoji: "\u{1F340}", name: "Four Leaf Clover", category: "Animals & Nature", keywords: ["clover", "luck", "lucky"] },

  // ── Food & Drink ──
  { emoji: "\u{1F34F}", name: "Green Apple", category: "Food & Drink", keywords: ["apple", "fruit", "green"] },
  { emoji: "\u{1F34E}", name: "Red Apple", category: "Food & Drink", keywords: ["apple", "fruit", "red"] },
  { emoji: "\u{1F350}", name: "Pear", category: "Food & Drink", keywords: ["pear", "fruit"] },
  { emoji: "\u{1F34A}", name: "Tangerine", category: "Food & Drink", keywords: ["orange", "tangerine", "fruit"] },
  { emoji: "\u{1F34B}", name: "Lemon", category: "Food & Drink", keywords: ["lemon", "citrus", "sour"] },
  { emoji: "\u{1F34C}", name: "Banana", category: "Food & Drink", keywords: ["banana", "fruit"] },
  { emoji: "\u{1F349}", name: "Watermelon", category: "Food & Drink", keywords: ["watermelon", "fruit", "summer"] },
  { emoji: "\u{1F347}", name: "Grapes", category: "Food & Drink", keywords: ["grapes", "fruit", "wine"] },
  { emoji: "\u{1F353}", name: "Strawberry", category: "Food & Drink", keywords: ["strawberry", "fruit", "berry"] },
  { emoji: "\u{1FAD0}", name: "Blueberries", category: "Food & Drink", keywords: ["blueberry", "fruit", "berry"] },
  { emoji: "\u{1F348}", name: "Melon", category: "Food & Drink", keywords: ["melon", "fruit"] },
  { emoji: "\u{1F352}", name: "Cherries", category: "Food & Drink", keywords: ["cherry", "fruit"] },
  { emoji: "\u{1F351}", name: "Peach", category: "Food & Drink", keywords: ["peach", "fruit"] },
  { emoji: "\u{1F96D}", name: "Mango", category: "Food & Drink", keywords: ["mango", "fruit", "tropical"] },
  { emoji: "\u{1F34D}", name: "Pineapple", category: "Food & Drink", keywords: ["pineapple", "fruit", "tropical"] },
  { emoji: "\u{1F965}", name: "Coconut", category: "Food & Drink", keywords: ["coconut", "tropical"] },
  { emoji: "\u{1F95D}", name: "Kiwi Fruit", category: "Food & Drink", keywords: ["kiwi", "fruit"] },
  { emoji: "\u{1F345}", name: "Tomato", category: "Food & Drink", keywords: ["tomato", "vegetable"] },
  { emoji: "\u{1F346}", name: "Eggplant", category: "Food & Drink", keywords: ["eggplant", "aubergine"] },
  { emoji: "\u{1F951}", name: "Avocado", category: "Food & Drink", keywords: ["avocado", "guacamole"] },
  { emoji: "\u{1F966}", name: "Broccoli", category: "Food & Drink", keywords: ["broccoli", "vegetable", "green"] },
  { emoji: "\u{1F33D}", name: "Ear of Corn", category: "Food & Drink", keywords: ["corn", "maize"] },
  { emoji: "\u{1F955}", name: "Carrot", category: "Food & Drink", keywords: ["carrot", "vegetable"] },
  { emoji: "\u{1F954}", name: "Potato", category: "Food & Drink", keywords: ["potato"] },
  { emoji: "\u{1F950}", name: "Croissant", category: "Food & Drink", keywords: ["croissant", "bread", "french"] },
  { emoji: "\u{1F35E}", name: "Bread", category: "Food & Drink", keywords: ["bread", "loaf"] },
  { emoji: "\u{1F9C0}", name: "Cheese Wedge", category: "Food & Drink", keywords: ["cheese"] },
  { emoji: "\u{1F95A}", name: "Egg", category: "Food & Drink", keywords: ["egg", "breakfast"] },
  { emoji: "\u{1F373}", name: "Cooking", category: "Food & Drink", keywords: ["egg", "frying", "cooking", "breakfast"] },
  { emoji: "\u{1F953}", name: "Bacon", category: "Food & Drink", keywords: ["bacon", "meat", "breakfast"] },
  { emoji: "\u{1F969}", name: "Cut of Meat", category: "Food & Drink", keywords: ["meat", "steak"] },
  { emoji: "\u{1F357}", name: "Poultry Leg", category: "Food & Drink", keywords: ["chicken", "drumstick", "meat"] },
  { emoji: "\u{1F32D}", name: "Hot Dog", category: "Food & Drink", keywords: ["hotdog", "sausage"] },
  { emoji: "\u{1F354}", name: "Hamburger", category: "Food & Drink", keywords: ["burger", "hamburger", "fast food"] },
  { emoji: "\u{1F35F}", name: "French Fries", category: "Food & Drink", keywords: ["fries", "chips", "fast food"] },
  { emoji: "\u{1F355}", name: "Pizza", category: "Food & Drink", keywords: ["pizza", "italian", "fast food"] },
  { emoji: "\u{1F363}", name: "Sushi", category: "Food & Drink", keywords: ["sushi", "japanese", "fish"] },
  { emoji: "\u{1F35C}", name: "Steaming Bowl", category: "Food & Drink", keywords: ["ramen", "noodles", "soup", "bowl"] },
  { emoji: "\u{1F370}", name: "Shortcake", category: "Food & Drink", keywords: ["cake", "dessert", "strawberry"] },
  { emoji: "\u{1F366}", name: "Soft Ice Cream", category: "Food & Drink", keywords: ["ice cream", "dessert", "sweet"] },
  { emoji: "\u{1F369}", name: "Doughnut", category: "Food & Drink", keywords: ["donut", "doughnut", "dessert"] },
  { emoji: "\u{1F36B}", name: "Chocolate Bar", category: "Food & Drink", keywords: ["chocolate", "candy", "sweet"] },
  { emoji: "\u{2615}", name: "Hot Beverage", category: "Food & Drink", keywords: ["coffee", "tea", "hot", "drink"] },
  { emoji: "\u{1F37A}", name: "Beer Mug", category: "Food & Drink", keywords: ["beer", "drink", "alcohol"] },
  { emoji: "\u{1F377}", name: "Wine Glass", category: "Food & Drink", keywords: ["wine", "drink", "alcohol"] },
  { emoji: "\u{1F378}", name: "Cocktail Glass", category: "Food & Drink", keywords: ["cocktail", "drink", "martini"] },
  { emoji: "\u{1F379}", name: "Tropical Drink", category: "Food & Drink", keywords: ["tropical", "drink", "cocktail"] },
  { emoji: "\u{1F9CB}", name: "Bubble Tea", category: "Food & Drink", keywords: ["boba", "bubble tea", "milk tea"] },

  // ── Travel & Places ──
  { emoji: "\u{1F697}", name: "Automobile", category: "Travel & Places", keywords: ["car", "drive", "vehicle"] },
  { emoji: "\u{1F695}", name: "Taxi", category: "Travel & Places", keywords: ["taxi", "cab"] },
  { emoji: "\u{1F699}", name: "Sport Utility Vehicle", category: "Travel & Places", keywords: ["suv", "car"] },
  { emoji: "\u{1F68C}", name: "Bus", category: "Travel & Places", keywords: ["bus", "transit"] },
  { emoji: "\u{1F3CE}\u{FE0F}", name: "Racing Car", category: "Travel & Places", keywords: ["racing", "car", "fast"] },
  { emoji: "\u{1F693}", name: "Police Car", category: "Travel & Places", keywords: ["police", "car"] },
  { emoji: "\u{1F691}", name: "Ambulance", category: "Travel & Places", keywords: ["ambulance", "hospital", "emergency"] },
  { emoji: "\u{1F692}", name: "Fire Engine", category: "Travel & Places", keywords: ["fire", "truck", "emergency"] },
  { emoji: "\u{1F69B}", name: "Articulated Lorry", category: "Travel & Places", keywords: ["truck", "semi", "delivery"] },
  { emoji: "\u{1F6B2}", name: "Bicycle", category: "Travel & Places", keywords: ["bike", "bicycle", "cycling"] },
  { emoji: "\u{1F6F4}", name: "Kick Scooter", category: "Travel & Places", keywords: ["scooter", "kick"] },
  { emoji: "\u{1F6F9}", name: "Skateboard", category: "Travel & Places", keywords: ["skateboard", "skate"] },
  { emoji: "\u{26FD}", name: "Fuel Pump", category: "Travel & Places", keywords: ["gas", "fuel", "petrol"] },
  { emoji: "\u{1F6A8}", name: "Police Car Light", category: "Travel & Places", keywords: ["siren", "police", "emergency"] },
  { emoji: "\u{1F6A5}", name: "Horizontal Traffic Light", category: "Travel & Places", keywords: ["traffic", "light"] },
  { emoji: "\u{1F6D1}", name: "Stop Sign", category: "Travel & Places", keywords: ["stop", "sign"] },
  { emoji: "\u{2693}", name: "Anchor", category: "Travel & Places", keywords: ["anchor", "ship", "boat"] },
  { emoji: "\u{26F5}", name: "Sailboat", category: "Travel & Places", keywords: ["boat", "sail", "sea"] },
  { emoji: "\u{1F6A4}", name: "Speedboat", category: "Travel & Places", keywords: ["boat", "speed", "water"] },
  { emoji: "\u{1F6F3}\u{FE0F}", name: "Passenger Ship", category: "Travel & Places", keywords: ["ship", "cruise"] },
  { emoji: "\u{1F6A2}", name: "Ship", category: "Travel & Places", keywords: ["ship", "boat", "ocean"] },
  { emoji: "\u{2708}\u{FE0F}", name: "Airplane", category: "Travel & Places", keywords: ["plane", "airplane", "flight", "travel"] },
  { emoji: "\u{1F681}", name: "Helicopter", category: "Travel & Places", keywords: ["helicopter", "fly"] },
  { emoji: "\u{1F680}", name: "Rocket", category: "Travel & Places", keywords: ["rocket", "space", "launch"] },
  { emoji: "\u{1F6F8}", name: "Flying Saucer", category: "Travel & Places", keywords: ["ufo", "alien", "space"] },
  { emoji: "\u{1F30D}", name: "Globe Showing Europe-Africa", category: "Travel & Places", keywords: ["earth", "globe", "world"] },
  { emoji: "\u{1F30E}", name: "Globe Showing Americas", category: "Travel & Places", keywords: ["earth", "globe", "world"] },
  { emoji: "\u{1F30F}", name: "Globe Showing Asia-Australia", category: "Travel & Places", keywords: ["earth", "globe", "world"] },
  { emoji: "\u{1F3E0}", name: "House", category: "Travel & Places", keywords: ["house", "home"] },
  { emoji: "\u{1F3E2}", name: "Office Building", category: "Travel & Places", keywords: ["office", "building", "work"] },
  { emoji: "\u{1F3E5}", name: "Hospital", category: "Travel & Places", keywords: ["hospital", "health"] },
  { emoji: "\u{1F3EB}", name: "School", category: "Travel & Places", keywords: ["school", "education"] },
  { emoji: "\u{1F3F0}", name: "Castle", category: "Travel & Places", keywords: ["castle", "princess"] },
  { emoji: "\u{26EA}", name: "Church", category: "Travel & Places", keywords: ["church", "religion"] },
  { emoji: "\u{1F5FC}", name: "Tokyo Tower", category: "Travel & Places", keywords: ["tokyo", "tower", "japan"] },
  { emoji: "\u{1F5FD}", name: "Statue of Liberty", category: "Travel & Places", keywords: ["liberty", "statue", "usa", "new york"] },
  { emoji: "\u{26F0}\u{FE0F}", name: "Mountain", category: "Travel & Places", keywords: ["mountain", "nature"] },
  { emoji: "\u{1F3D6}\u{FE0F}", name: "Beach with Umbrella", category: "Travel & Places", keywords: ["beach", "vacation", "summer"] },
  { emoji: "\u{1F305}", name: "Sunrise", category: "Travel & Places", keywords: ["sunrise", "morning", "sun"] },
  { emoji: "\u{1F307}", name: "Sunset", category: "Travel & Places", keywords: ["sunset", "evening", "city"] },
  { emoji: "\u{1F303}", name: "Night with Stars", category: "Travel & Places", keywords: ["night", "stars", "city"] },
  { emoji: "\u{1F309}", name: "Bridge at Night", category: "Travel & Places", keywords: ["bridge", "night", "city"] },
  { emoji: "\u{2B50}", name: "Star", category: "Travel & Places", keywords: ["star", "favorite", "gold"] },
  { emoji: "\u{1F31F}", name: "Glowing Star", category: "Travel & Places", keywords: ["star", "sparkle", "glow"] },
  { emoji: "\u{2600}\u{FE0F}", name: "Sun", category: "Travel & Places", keywords: ["sun", "weather", "sunny"] },
  { emoji: "\u{1F324}\u{FE0F}", name: "Sun Behind Small Cloud", category: "Travel & Places", keywords: ["sun", "cloud", "weather"] },
  { emoji: "\u{26C5}", name: "Sun Behind Cloud", category: "Travel & Places", keywords: ["cloud", "sun", "weather"] },
  { emoji: "\u{1F327}\u{FE0F}", name: "Cloud with Rain", category: "Travel & Places", keywords: ["rain", "cloud", "weather"] },
  { emoji: "\u{2744}\u{FE0F}", name: "Snowflake", category: "Travel & Places", keywords: ["snow", "winter", "cold"] },
  { emoji: "\u{1F525}", name: "Fire", category: "Travel & Places", keywords: ["fire", "hot", "lit", "flame"] },

  // ── Objects ──
  { emoji: "\u{231A}", name: "Watch", category: "Objects", keywords: ["watch", "time"] },
  { emoji: "\u{1F4F1}", name: "Mobile Phone", category: "Objects", keywords: ["phone", "mobile", "cell"] },
  { emoji: "\u{1F4BB}", name: "Laptop", category: "Objects", keywords: ["laptop", "computer", "pc"] },
  { emoji: "\u{2328}\u{FE0F}", name: "Keyboard", category: "Objects", keywords: ["keyboard", "type"] },
  { emoji: "\u{1F5A5}\u{FE0F}", name: "Desktop Computer", category: "Objects", keywords: ["computer", "desktop", "pc"] },
  { emoji: "\u{1F5A8}\u{FE0F}", name: "Printer", category: "Objects", keywords: ["printer", "print"] },
  { emoji: "\u{1F579}\u{FE0F}", name: "Joystick", category: "Objects", keywords: ["joystick", "game", "gaming"] },
  { emoji: "\u{1F4BD}", name: "Computer Disk", category: "Objects", keywords: ["disk", "minidisk", "save"] },
  { emoji: "\u{1F4BE}", name: "Floppy Disk", category: "Objects", keywords: ["floppy", "disk", "save", "retro"] },
  { emoji: "\u{1F4BF}", name: "Optical Disk", category: "Objects", keywords: ["cd", "disc", "dvd"] },
  { emoji: "\u{1F4C0}", name: "DVD", category: "Objects", keywords: ["dvd", "disc"] },
  { emoji: "\u{1F4F7}", name: "Camera", category: "Objects", keywords: ["camera", "photo"] },
  { emoji: "\u{1F4F8}", name: "Camera with Flash", category: "Objects", keywords: ["camera", "flash", "photo"] },
  { emoji: "\u{1F4F9}", name: "Video Camera", category: "Objects", keywords: ["video", "camera", "record"] },
  { emoji: "\u{1F3A5}", name: "Movie Camera", category: "Objects", keywords: ["movie", "film", "camera"] },
  { emoji: "\u{1F4FA}", name: "Television", category: "Objects", keywords: ["tv", "television", "watch"] },
  { emoji: "\u{1F4FB}", name: "Radio", category: "Objects", keywords: ["radio", "music"] },
  { emoji: "\u{1F3A4}", name: "Microphone", category: "Objects", keywords: ["microphone", "sing", "karaoke"] },
  { emoji: "\u{1F3A7}", name: "Headphone", category: "Objects", keywords: ["headphone", "music", "listen"] },
  { emoji: "\u{1F3B5}", name: "Musical Note", category: "Objects", keywords: ["music", "note", "song"] },
  { emoji: "\u{1F3B6}", name: "Musical Notes", category: "Objects", keywords: ["music", "notes", "melody"] },
  { emoji: "\u{1F3B8}", name: "Guitar", category: "Objects", keywords: ["guitar", "music", "rock"] },
  { emoji: "\u{1F3B9}", name: "Musical Keyboard", category: "Objects", keywords: ["piano", "keyboard", "music"] },
  { emoji: "\u{1F3BA}", name: "Trumpet", category: "Objects", keywords: ["trumpet", "music", "horn"] },
  { emoji: "\u{1F941}", name: "Drum", category: "Objects", keywords: ["drum", "music", "beat"] },
  { emoji: "\u{1F4D6}", name: "Open Book", category: "Objects", keywords: ["book", "read", "open"] },
  { emoji: "\u{1F4DA}", name: "Books", category: "Objects", keywords: ["books", "library", "read"] },
  { emoji: "\u{1F4DD}", name: "Memo", category: "Objects", keywords: ["memo", "note", "write"] },
  { emoji: "\u{270F}\u{FE0F}", name: "Pencil", category: "Objects", keywords: ["pencil", "write", "edit"] },
  { emoji: "\u{1F58A}\u{FE0F}", name: "Pen", category: "Objects", keywords: ["pen", "write"] },
  { emoji: "\u{1F4E7}", name: "E-Mail", category: "Objects", keywords: ["email", "mail", "letter"] },
  { emoji: "\u{1F4E6}", name: "Package", category: "Objects", keywords: ["package", "box", "delivery"] },
  { emoji: "\u{1F4B0}", name: "Money Bag", category: "Objects", keywords: ["money", "bag", "rich", "dollar"] },
  { emoji: "\u{1F4B3}", name: "Credit Card", category: "Objects", keywords: ["credit card", "payment"] },
  { emoji: "\u{1F4B8}", name: "Money with Wings", category: "Objects", keywords: ["money", "spend", "dollar", "fly"] },
  { emoji: "\u{1F4A1}", name: "Light Bulb", category: "Objects", keywords: ["idea", "light", "bulb", "bright"] },
  { emoji: "\u{1F526}", name: "Flashlight", category: "Objects", keywords: ["flashlight", "torch", "light"] },
  { emoji: "\u{1F512}", name: "Locked", category: "Objects", keywords: ["lock", "secure", "locked"] },
  { emoji: "\u{1F513}", name: "Unlocked", category: "Objects", keywords: ["unlock", "open"] },
  { emoji: "\u{1F511}", name: "Key", category: "Objects", keywords: ["key", "lock", "password"] },
  { emoji: "\u{1F528}", name: "Hammer", category: "Objects", keywords: ["hammer", "tool", "build"] },
  { emoji: "\u{1F527}", name: "Wrench", category: "Objects", keywords: ["wrench", "tool", "fix"] },
  { emoji: "\u{2699}\u{FE0F}", name: "Gear", category: "Objects", keywords: ["gear", "settings", "cog"] },
  { emoji: "\u{1F50D}", name: "Magnifying Glass Tilted Left", category: "Objects", keywords: ["search", "magnify", "find"] },
  { emoji: "\u{1F50E}", name: "Magnifying Glass Tilted Right", category: "Objects", keywords: ["search", "magnify"] },
  { emoji: "\u{2764}\u{FE0F}\u{200D}\u{1FA79}", name: "Mending Heart", category: "Objects", keywords: ["heart", "mend", "heal"] },
  { emoji: "\u{1F4CA}", name: "Bar Chart", category: "Objects", keywords: ["chart", "graph", "data", "stats"] },
  { emoji: "\u{1F4C8}", name: "Chart Increasing", category: "Objects", keywords: ["chart", "up", "growth"] },
  { emoji: "\u{1F4C9}", name: "Chart Decreasing", category: "Objects", keywords: ["chart", "down", "decline"] },
  { emoji: "\u{1F4CC}", name: "Pushpin", category: "Objects", keywords: ["pin", "pushpin"] },
  { emoji: "\u{1F4CE}", name: "Paperclip", category: "Objects", keywords: ["paperclip", "attachment"] },

  // ── Symbols ──
  { emoji: "\u{2764}\u{FE0F}", name: "Red Heart", category: "Symbols", keywords: ["heart", "love", "red"] },
  { emoji: "\u{1F9E1}", name: "Orange Heart", category: "Symbols", keywords: ["heart", "orange"] },
  { emoji: "\u{1F49B}", name: "Yellow Heart", category: "Symbols", keywords: ["heart", "yellow"] },
  { emoji: "\u{1F49A}", name: "Green Heart", category: "Symbols", keywords: ["heart", "green"] },
  { emoji: "\u{1F499}", name: "Blue Heart", category: "Symbols", keywords: ["heart", "blue"] },
  { emoji: "\u{1F49C}", name: "Purple Heart", category: "Symbols", keywords: ["heart", "purple"] },
  { emoji: "\u{1F5A4}", name: "Black Heart", category: "Symbols", keywords: ["heart", "black"] },
  { emoji: "\u{1F90D}", name: "White Heart", category: "Symbols", keywords: ["heart", "white"] },
  { emoji: "\u{1F90E}", name: "Brown Heart", category: "Symbols", keywords: ["heart", "brown"] },
  { emoji: "\u{1F494}", name: "Broken Heart", category: "Symbols", keywords: ["heart", "broken", "sad"] },
  { emoji: "\u{2763}\u{FE0F}", name: "Heart Exclamation", category: "Symbols", keywords: ["heart", "exclamation"] },
  { emoji: "\u{1F495}", name: "Two Hearts", category: "Symbols", keywords: ["heart", "love", "two"] },
  { emoji: "\u{1F49E}", name: "Revolving Hearts", category: "Symbols", keywords: ["heart", "revolving", "love"] },
  { emoji: "\u{1F493}", name: "Beating Heart", category: "Symbols", keywords: ["heart", "beating", "love"] },
  { emoji: "\u{1F497}", name: "Growing Heart", category: "Symbols", keywords: ["heart", "growing", "love"] },
  { emoji: "\u{1F496}", name: "Sparkling Heart", category: "Symbols", keywords: ["heart", "sparkle", "love"] },
  { emoji: "\u{1F498}", name: "Heart with Arrow", category: "Symbols", keywords: ["heart", "arrow", "cupid"] },
  { emoji: "\u{1F49D}", name: "Heart with Ribbon", category: "Symbols", keywords: ["heart", "gift", "ribbon"] },
  { emoji: "\u{1F49F}", name: "Heart Decoration", category: "Symbols", keywords: ["heart", "decoration"] },
  { emoji: "\u{262E}\u{FE0F}", name: "Peace Symbol", category: "Symbols", keywords: ["peace", "symbol"] },
  { emoji: "\u{271D}\u{FE0F}", name: "Latin Cross", category: "Symbols", keywords: ["cross", "religion", "christian"] },
  { emoji: "\u{262A}\u{FE0F}", name: "Star and Crescent", category: "Symbols", keywords: ["islam", "muslim", "crescent"] },
  { emoji: "\u{2638}\u{FE0F}", name: "Wheel of Dharma", category: "Symbols", keywords: ["dharma", "buddhism"] },
  { emoji: "\u{2721}\u{FE0F}", name: "Star of David", category: "Symbols", keywords: ["star", "david", "jewish"] },
  { emoji: "\u{262F}\u{FE0F}", name: "Yin Yang", category: "Symbols", keywords: ["yin", "yang", "balance"] },
  { emoji: "\u{267E}\u{FE0F}", name: "Infinity", category: "Symbols", keywords: ["infinity", "forever"] },
  { emoji: "\u{2648}", name: "Aries", category: "Symbols", keywords: ["aries", "zodiac"] },
  { emoji: "\u{2649}", name: "Taurus", category: "Symbols", keywords: ["taurus", "zodiac"] },
  { emoji: "\u{264A}", name: "Gemini", category: "Symbols", keywords: ["gemini", "zodiac"] },
  { emoji: "\u{264B}", name: "Cancer", category: "Symbols", keywords: ["cancer", "zodiac"] },
  { emoji: "\u{264C}", name: "Leo", category: "Symbols", keywords: ["leo", "zodiac"] },
  { emoji: "\u{264D}", name: "Virgo", category: "Symbols", keywords: ["virgo", "zodiac"] },
  { emoji: "\u{264E}", name: "Libra", category: "Symbols", keywords: ["libra", "zodiac"] },
  { emoji: "\u{264F}", name: "Scorpio", category: "Symbols", keywords: ["scorpio", "zodiac"] },
  { emoji: "\u{2650}", name: "Sagittarius", category: "Symbols", keywords: ["sagittarius", "zodiac"] },
  { emoji: "\u{2651}", name: "Capricorn", category: "Symbols", keywords: ["capricorn", "zodiac"] },
  { emoji: "\u{2652}", name: "Aquarius", category: "Symbols", keywords: ["aquarius", "zodiac"] },
  { emoji: "\u{2653}", name: "Pisces", category: "Symbols", keywords: ["pisces", "zodiac"] },
  { emoji: "\u{269B}\u{FE0F}", name: "Atom Symbol", category: "Symbols", keywords: ["atom", "science"] },
  { emoji: "\u{2622}\u{FE0F}", name: "Radioactive", category: "Symbols", keywords: ["radioactive", "nuclear"] },
  { emoji: "\u{2623}\u{FE0F}", name: "Biohazard", category: "Symbols", keywords: ["biohazard", "danger"] },
  { emoji: "\u{2705}", name: "Check Mark Button", category: "Symbols", keywords: ["check", "yes", "done"] },
  { emoji: "\u{274C}", name: "Cross Mark", category: "Symbols", keywords: ["x", "no", "wrong"] },
  { emoji: "\u{274E}", name: "Cross Mark Button", category: "Symbols", keywords: ["x", "no"] },
  { emoji: "\u{2753}", name: "Red Question Mark", category: "Symbols", keywords: ["question", "?"] },
  { emoji: "\u{2757}", name: "Red Exclamation Mark", category: "Symbols", keywords: ["exclamation", "!", "alert"] },
  { emoji: "\u{1F4AF}", name: "Hundred Points", category: "Symbols", keywords: ["100", "perfect", "score"] },
  { emoji: "\u{1F51E}", name: "No One Under Eighteen", category: "Symbols", keywords: ["18", "adult", "nsfw"] },
  { emoji: "\u{267B}\u{FE0F}", name: "Recycling Symbol", category: "Symbols", keywords: ["recycle", "environment", "green"] },

  // ── Flags ──
  { emoji: "\u{1F3F3}\u{FE0F}", name: "White Flag", category: "Flags", keywords: ["flag", "white", "surrender"] },
  { emoji: "\u{1F3F4}", name: "Black Flag", category: "Flags", keywords: ["flag", "black"] },
  { emoji: "\u{1F6A9}", name: "Triangular Flag", category: "Flags", keywords: ["flag", "red", "marker"] },
  { emoji: "\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}", name: "Rainbow Flag", category: "Flags", keywords: ["rainbow", "pride", "lgbtq"] },
  { emoji: "\u{1F3F3}\u{FE0F}\u{200D}\u{26A7}\u{FE0F}", name: "Transgender Flag", category: "Flags", keywords: ["transgender", "pride", "flag"] },
  { emoji: "\u{1F1FA}\u{1F1F8}", name: "Flag: United States", category: "Flags", keywords: ["us", "usa", "america", "united states"] },
  { emoji: "\u{1F1EC}\u{1F1E7}", name: "Flag: United Kingdom", category: "Flags", keywords: ["uk", "britain", "england"] },
  { emoji: "\u{1F1EB}\u{1F1F7}", name: "Flag: France", category: "Flags", keywords: ["france", "french"] },
  { emoji: "\u{1F1E9}\u{1F1EA}", name: "Flag: Germany", category: "Flags", keywords: ["germany", "german"] },
  { emoji: "\u{1F1EE}\u{1F1F9}", name: "Flag: Italy", category: "Flags", keywords: ["italy", "italian"] },
  { emoji: "\u{1F1EA}\u{1F1F8}", name: "Flag: Spain", category: "Flags", keywords: ["spain", "spanish"] },
  { emoji: "\u{1F1F5}\u{1F1F9}", name: "Flag: Portugal", category: "Flags", keywords: ["portugal", "portuguese"] },
  { emoji: "\u{1F1E7}\u{1F1F7}", name: "Flag: Brazil", category: "Flags", keywords: ["brazil", "brazilian"] },
  { emoji: "\u{1F1EF}\u{1F1F5}", name: "Flag: Japan", category: "Flags", keywords: ["japan", "japanese"] },
  { emoji: "\u{1F1F0}\u{1F1F7}", name: "Flag: South Korea", category: "Flags", keywords: ["korea", "south korea", "korean"] },
  { emoji: "\u{1F1E8}\u{1F1F3}", name: "Flag: China", category: "Flags", keywords: ["china", "chinese"] },
  { emoji: "\u{1F1EE}\u{1F1F3}", name: "Flag: India", category: "Flags", keywords: ["india", "indian"] },
  { emoji: "\u{1F1F7}\u{1F1FA}", name: "Flag: Russia", category: "Flags", keywords: ["russia", "russian"] },
  { emoji: "\u{1F1E8}\u{1F1E6}", name: "Flag: Canada", category: "Flags", keywords: ["canada", "canadian"] },
  { emoji: "\u{1F1E6}\u{1F1FA}", name: "Flag: Australia", category: "Flags", keywords: ["australia", "australian"] },
  { emoji: "\u{1F1F2}\u{1F1FD}", name: "Flag: Mexico", category: "Flags", keywords: ["mexico", "mexican"] },
  { emoji: "\u{1F1F8}\u{1F1EA}", name: "Flag: Sweden", category: "Flags", keywords: ["sweden", "swedish"] },
  { emoji: "\u{1F1F3}\u{1F1F4}", name: "Flag: Norway", category: "Flags", keywords: ["norway", "norwegian"] },
  { emoji: "\u{1F1E8}\u{1F1ED}", name: "Flag: Switzerland", category: "Flags", keywords: ["switzerland", "swiss"] },
  { emoji: "\u{1F1F3}\u{1F1F1}", name: "Flag: Netherlands", category: "Flags", keywords: ["netherlands", "dutch"] },
  { emoji: "\u{1F1F9}\u{1F1F7}", name: "Flag: Turkey", category: "Flags", keywords: ["turkey", "turkish"] },
  { emoji: "\u{1F1F8}\u{1F1E6}", name: "Flag: Saudi Arabia", category: "Flags", keywords: ["saudi", "arabia"] },
  { emoji: "\u{1F1E6}\u{1F1EA}", name: "Flag: United Arab Emirates", category: "Flags", keywords: ["uae", "emirates", "dubai"] },
  { emoji: "\u{1F1F9}\u{1F1ED}", name: "Flag: Thailand", category: "Flags", keywords: ["thailand", "thai"] },
  { emoji: "\u{1F1FB}\u{1F1F3}", name: "Flag: Vietnam", category: "Flags", keywords: ["vietnam", "vietnamese"] },
];

export function searchEmojis(query: string, emojis: EmojiData[]): EmojiData[] {
  if (!query.trim()) return emojis;
  const lower = query.toLowerCase().trim();
  return emojis.filter(
    (e) =>
      e.name.toLowerCase().includes(lower) ||
      e.keywords.some((k) => k.includes(lower))
  );
}

export function getEmojisByCategory(category: EmojiCategory): EmojiData[] {
  return ALL_EMOJIS.filter((e) => e.category === category);
}

const RECENT_KEY = "emoji-picker-recent";
const MAX_RECENT = 32;

export function getRecentEmojis(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const stored = localStorage.getItem(RECENT_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

export function addRecentEmoji(emoji: string): string[] {
  const recent = getRecentEmojis().filter((e) => e !== emoji);
  recent.unshift(emoji);
  const trimmed = recent.slice(0, MAX_RECENT);
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(trimmed));
  } catch {
    // localStorage full or unavailable
  }
  return trimmed;
}
