import type { Locale } from "@/i18n/config";

const KO_TOOL_UI_TEXT: Record<string, string> = {
  "Input": "입력",
  "Output": "출력",
  "Load Sample": "샘플 불러오기",
  "Copy": "복사",
  "Copy All": "전체 복사",
  "Copy HTML": "HTML 복사",
  "Copy Text": "텍스트 복사",
  "Copy Payload": "페이로드 복사",
  "Copy Result": "결과 복사",
  "Download": "다운로드",
  "Download Report": "리포트 다운로드",
  "Preview": "미리보기",
  "Indent:": "들여쓰기:",
  "Format": "포맷",
  "Minify": "압축",
  "Validate": "검증",
  "Sort Keys": "키 정렬",
  "2 spaces": "공백 2칸",
  "4 spaces": "공백 4칸",
  "Tab": "탭",
  "Valid JSON": "유효한 JSON",
  "Invalid JSON": "유효하지 않은 JSON",
  "Text": "텍스트",
  "File": "파일",
  "Image": "이미지",
  "Encode": "인코드",
  "Decode": "디코드",
  "Convert": "변환",
  "Base64 Output": "Base64 출력",
  "Data URI": "데이터 URI",
  "JWT Token": "JWT 토큰",
  "Expired": "만료됨",
  "Valid": "유효함",
  "Token expired": "토큰 만료",
  "Token expires": "토큰 만료 예정",
  "Header": "헤더",
  "Payload": "페이로드",
  "Signature": "서명",
  "Could not load exchange rates": "환율 데이터를 불러올 수 없습니다",
  "Retry": "다시 시도",
  "Amount": "금액",
  "From": "기준 통화",
  "To": "대상 통화",
  "Last updated": "마지막 업데이트",
  "Popular Exchange Rates": "주요 환율",
  "Pair": "통화쌍",
  "Rate": "환율",
  "Reverse": "역환율",
  "Search currency...": "통화를 검색하세요...",
  "No currencies found": "일치하는 통화가 없습니다",
  "Swap currencies": "통화 바꾸기",
  "Swap units": "단위 바꾸기",
  "Value": "값",
  "Result": "결과",
  "All": "전체",
  "Color picker": "색상 선택기",
  "Color preview": "색상 미리보기",
  "Opacity": "투명도",
  "Color Values": "색상 값",
  "Contrast Checker (WCAG)": "명도 대비 검사기 (WCAG)",
  "Foreground": "전경색",
  "Background": "배경색",
  "Sample Text — Aa Bb Cc 123": "샘플 텍스트 — Aa Bb Cc 123",
  "Palette Generator": "팔레트 생성기",
  "complementary": "보색",
  "analogous": "유사색",
  "triadic": "삼각 배색",
  "Loan Amount": "대출 금액",
  "Repayment Method": "상환 방식",
  "Monthly Payment": "월 상환액",
  "First Monthly Payment": "첫 달 상환액",
  "Total Payment": "총 상환액",
  "Total Interest": "총 이자",
  "Principal vs Interest": "원금 대비 이자",
  "Balance Over Time": "기간별 잔액",
  "Show": "보기",
  "Hide": "숨기기",
  "Amortization Schedule": "상환 스케줄",
  "Month": "월",
  "Payment": "납입액",
  "Principal": "원금",
  "Interest": "이자",
  "Balance": "잔액",
  "Initial Investment": "초기 투자금",
  "Compounding Frequency": "복리 주기",
  "Monthly Contribution (optional)": "월 납입금 (선택)",
  "Final Amount": "최종 금액",
  "Total Invested": "총 투자금",
  "Interest Earned": "누적 이자",
  "Growth Over Time": "기간별 성장",
  "Year": "연도",
  "Underweight": "저체중",
  "Normal": "정상",
  "Overweight": "과체중",
  "Obese": "비만",
  "BMI Prime": "BMI 프라임",
  "Healthy Weight Range": "권장 체중 범위",
  "Disclaimer:": "안내:",
  "Unit": "단위",
  "Words": "단어",
  "Sentences": "문장",
  "Paragraphs": "문단",
  "Quantity": "수량",
  "Start with \"Lorem ipsum\"": "\"Lorem ipsum\"으로 시작",
  "Wrap in HTML <p> tags": "HTML <p> 태그로 감싸기",
  "Generate": "생성",
  "Click Generate to create Lorem Ipsum text...": "생성을 눌러 Lorem Ipsum 텍스트를 만드세요...",
  "Markdown Cheatsheet": "Markdown 치트시트",
  "Element": "요소",
  "Syntax": "문법",
  "Heading 1": "제목 1",
  "Heading 2": "제목 2",
  "Heading 3": "제목 3",
  "Bold": "굵게",
  "Italic": "기울임",
  "Strikethrough": "취소선",
  "Link": "링크",
  "Inline Code": "인라인 코드",
  "Code Block": "코드 블록",
  "Blockquote": "인용문",
  "Unordered List": "순서 없는 목록",
  "Ordered List": "순서 있는 목록",
  "Horizontal Rule": "구분선",
  "Table": "표",
  "Pattern": "패턴",
  "Presets": "프리셋",
  "Test String": "테스트 문자열",
  "Match Highlighting": "매치 하이라이트",
  "Match Details": "매치 상세",
  "Index": "인덱스",
  "Full Match": "전체 일치",
  "Groups": "그룹",
  "Replacement (optional)": "치환 문자열 (선택)",
  "Replace Result": "치환 결과",
  "Original": "원본",
  "Modified": "수정본",
  "Compare": "비교",
  "Clear": "지우기",
  "Inline": "인라인",
  "Side-by-side": "양쪽 비교",
  "Text Input": "텍스트 입력",
  "or": "또는",
  "Uppercase output": "대문자 출력",
  "Computing hashes…": "해시를 계산하는 중...",
  "Algorithm": "알고리즘",
  "Hash Value": "해시 값",
  "Date of Birth": "생년월일",
  "Your Age": "현재 나이",
  "years": "년",
  "months": "개월",
  "days": "일",
  "Total Days": "총 일수",
  "Total Hours": "총 시간",
  "Total Minutes": "총 분",
  "Next Birthday": "다음 생일",
  "Today!": "오늘!",
  "Born On": "태어난 요일",
  "Zodiac": "별자리",
  "Details": "상세 정보",
  "Day of Week": "요일",
  "Western Zodiac": "서양 별자리",
  "Chinese Zodiac": "띠",
  "Next Birthday In": "다음 생일까지",
  "Years": "년",
  "Months": "개월",
  "Days": "일",
  "Day": "일",
  "Date Interval Calculator": "날짜 간격 계산기",
  "Calculate the time between any two dates": "두 날짜 사이의 기간을 계산합니다",
  "Start Date": "시작 날짜",
  "End Date": "종료 날짜",
  "What is Y% of X?": "X의 Y%는 얼마인가요?",
  "Find a percentage of any number": "어떤 숫자의 퍼센트를 계산합니다",
  "Number (X)": "숫자 (X)",
  "Percentage (Y)": "퍼센트 (Y)",
  "X is what % of Y?": "X는 Y의 몇 %인가요?",
  "Find what percentage one number is of another": "한 숫자가 다른 숫자의 몇 퍼센트인지 계산합니다",
  "Part (X)": "부분 (X)",
  "Whole (Y)": "전체 (Y)",
  "Percentage Change": "퍼센트 변화",
  "Calculate the % increase or decrease between two values": "두 값 사이의 증가율 또는 감소율을 계산합니다",
  "From (original)": "기준값",
  "To (new)": "변경값",
  "Apply Percentage (Discount / Markup)": "퍼센트 적용 (할인 / 가산)",
  "Add or subtract a percentage from a number": "숫자에 퍼센트를 더하거나 뺍니다",
  "Original value": "원래 값",
  "Percentage": "퍼센트",
  "After discount": "할인 적용 후",
  "After markup": "가산 적용 후",
  "You save": "절약 금액",
  "Added": "추가 금액",
  "Mode": "모드",
  "Discount": "할인",
  "Markup": "가산",
  "Bill Amount": "금액",
  "Tip Percentage": "팁 비율",
  "Custom:": "직접 입력:",
  "Enter %": "% 입력",
  "Split Between": "인원 수",
  "person": "명",
  "people": "명",
  "Round Up": "반올림",
  "Round each person's total to the nearest dollar": "1인당 금액을 가장 가까운 달러로 반올림합니다",
  "Tip Amount": "팁 금액",
  "Total": "총액",
  "Tip / Person": "1인당 팁",
  "Total / Person": "1인당 총액",
  "Each Person Pays": "1인당 결제 금액",
  "You Pay": "최종 결제 금액",
  "Mode:": "모드:",
  "(recommended)": "(권장)",
  "Text to Encode": "인코딩할 텍스트",
  "URL to Decode": "디코딩할 URL",
  "Encoded Output": "인코딩 결과",
  "Decoded Output": "디코딩 결과",
  "Result Date": "결과 날짜",
  "Start": "시작",
  "End": "종료",
  "Base Date": "기준 날짜",
  "Operation": "연산",
  "+ Add": "+ 더하기",
  "- Subtract": "- 빼기",
  "Business days only (exclude Sat & Sun)": "영업일만 계산 (토/일 제외)",
  "Include end date in count": "종료일 포함",
  "Weeks": "주",
  "Daily": "매일",
  "Monthly": "매월",
  "Quarterly": "분기별",
  "Semi-Annually": "반기별",
  "Annually": "매년",
  "Metric (cm / kg)": "미터법 (cm / kg)",
  "Imperial (ft-in / lbs)": "야드파운드법 (ft-in / lbs)",
  "Height": "키",
  "Height (cm)": "키 (cm)",
  "Weight": "몸무게",
  "Your BMI": "BMI",
  "Equal Payment": "원리금균등",
  "Equal Principal": "원금균등",
  "Bullet": "만기일시",
  "Length": "길이",
  "Temperature": "온도",
  "Volume": "부피",
  "Area": "면적",
  "Speed": "속도",
  "Data": "데이터",
  "Time": "시간",
  "Millimeter": "밀리미터",
  "Centimeter": "센티미터",
  "Meter": "미터",
  "Kilometer": "킬로미터",
  "Inch": "인치",
  "Foot": "피트",
  "Yard": "야드",
  "Mile": "마일",
  "Milligram": "밀리그램",
  "Gram": "그램",
  "Kilogram": "킬로그램",
  "Ounce": "온스",
  "Pound": "파운드",
  "Metric Ton": "톤",
  "Celsius": "섭씨",
  "Fahrenheit": "화씨",
  "Kelvin": "켈빈",
  "Milliliter": "밀리리터",
  "Liter": "리터",
  "US Gallon": "미국 갤런",
  "US Fluid Ounce": "미국 액량 온스",
  "US Cup": "미국 컵",
  "Tablespoon": "테이블스푼",
  "Teaspoon": "티스푼",
  "Square Millimeter": "제곱밀리미터",
  "Square Centimeter": "제곱센티미터",
  "Square Meter": "제곱미터",
  "Square Kilometer": "제곱킬로미터",
  "Square Inch": "제곱인치",
  "Square Foot": "제곱피트",
  "Acre": "에이커",
  "Hectare": "헥타르",
  "Meters per Second": "초속 미터",
  "Kilometers per Hour": "시속 킬로미터",
  "Miles per Hour": "시속 마일",
  "Knot": "노트",
  "Feet per Second": "초속 피트",
  "Bit": "비트",
  "Byte": "바이트",
  "Kilobyte": "킬로바이트",
  "Kilobyte (KB)": "킬로바이트 (KB)",
  "Megabyte": "메가바이트",
  "Megabyte (MB)": "메가바이트 (MB)",
  "Gigabyte": "기가바이트",
  "Gigabyte (GB)": "기가바이트 (GB)",
  "Terabyte": "테라바이트",
  "Terabyte (TB)": "테라바이트 (TB)",
  "Petabyte": "페타바이트",
  "Petabyte (PB)": "페타바이트 (PB)",
  "Exabyte": "엑사바이트",
  "Exabyte (EB)": "엑사바이트 (EB)",
  "Second": "초",
  "Minute": "분",
  "Hour": "시간",
  "Week": "주",
  "Month (30 days)": "월 (30일)",
  "Year (365 days)": "년 (365일)",
  "Text to hash…": "해시할 텍스트를 입력하세요…",
  "Enter text to encode…": "인코딩할 텍스트를 입력하세요…",
  "Enter Base64 to decode…": "디코드할 Base64를 입력하세요…",
  "Drop a file here or click to browse": "파일을 여기에 놓거나 클릭해서 선택하세요",
  "Hashing file:": "해시 계산 중인 파일:",
  "Paste original text here...": "원본 텍스트를 붙여넣으세요...",
  "Paste modified text here...": "수정된 텍스트를 붙여넣으세요...",
  "Enter regex pattern...": "정규식 패턴을 입력하세요...",
  "Enter text to test against the regex...": "정규식과 비교할 텍스트를 입력하세요...",
  "Enter replacement string (use $1, $2 for groups)...": "치환 문자열을 입력하세요 (그룹은 $1, $2 사용)...",
  "Type or paste your text here...": "텍스트를 입력하거나 붙여넣으세요...",
  "Type or paste your text here…": "텍스트를 입력하거나 붙여넣으세요…",
  "Converted text will appear here…": "변환된 텍스트가 여기에 표시됩니다…",
  "Type or paste Markdown here...": "Markdown을 입력하거나 붙여넣으세요...",
  "Paste your JWT here (eyJhbGciOiJIUz...)": "JWT를 붙여넣으세요 (eyJhbGciOiJIUz...)",
  "Paste JSON here, e.g. {\"key\": \"value\"}": "JSON을 붙여넣으세요. 예: {\"key\": \"value\"}",
  "Drop a .json file here or click to browse": ".json 파일을 여기에 놓거나 클릭해서 선택하세요",
  "Drop any file here or click to browse": "파일을 여기에 놓거나 클릭해서 선택하세요",
  "Drop an image here or click to browse": "이미지를 여기에 놓거나 클릭해서 선택하세요",
  "Output will appear here…": "결과가 여기에 표시됩니다…",
  "No Spaces": "공백 제외",
  "Reading Time": "읽기 시간",
  "Speaking Time": "말하기 시간",
  "Flesch Reading Ease": "Flesch 읽기 난이도",
  "Keyword Density (Top 10)": "키워드 밀도 (상위 10개)",
  "Keyword": "키워드",
  "Count": "횟수",
  "Density": "밀도",
  "Start typing to see keyword density analysis.": "입력하면 키워드 밀도 분석이 표시됩니다.",
  "Enter a value": "값을 입력하세요",
  "Conversion Results": "변환 결과",
  "Note:": "참고:",
  "All units use binary (×1024) conversion.": "모든 단위는 이진 기준(×1024)으로 변환됩니다.",
};

export function getToolUiText(locale: Locale) {
  return (text: string) =>
    locale === "ko" ? (KO_TOOL_UI_TEXT[text] ?? text) : text;
}
